version: '3'
services:
  api:
    container_name: backend
    build: ./Application
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    networks:
      - backend
    depends_on:
      - db_service
networks:
  backend:
    driver: bridge

