version: '3'
services:
  api:
    container_name: api_backend
    build: .
    volumes:
      - ./:/app
    ports:
      - '5000:5000'
    networks:
      - backend
    depends_on:
      - db_service
  db_service:
    container_name: db_service
    image: postgres
    environment:
      POSTGRES_USER: "mesquitadev"
      POSTGRES_PASSWORD: "1:@7519!@"
    ports:
      - "5432:5432"
    volumes:
      - /PostgreSQL:/var/lib/postgresql/data
    networks:
      - backend
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "mesquitadev@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1qaz2wsxasd"
    ports:
      - "8080:80"
    depends_on:
      - db_service
    networks:
      - backend
networks:
  backend:
    driver: bridge

