version: '3'
services:
  web:
    build: .
    ports:
    - "80:80"
    volumes:
    - .:/code
    networks:
      - adonisjs
    depends_on:
     - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "5432:5432"
    volumes:
      - /postgres:/var/lib/postgresql/data
    networks:
      - adonisjs
networks:
  adonisjs:
    driver: bridge
