version: 2.1
workflows:
  version: 2
  build_and_deploy_workflow:
    jobs:
       - build_and_deploy_job:
          filters:
            branches:
              only:
                - main
jobs:
  build_and_deploy_job:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout

      - run:
          name: backend
          command: |
            echo "Hello, world"
      - run:
        name: deploy to app engine
        command: |
          gcloud config set project bb-multichecker
          gcloud config set compute/region southamerica-east1
          gcloup app deploy
